name: Deploy to IIS

on:
  push:
    branches:
      - main   # or master, adjust to your default branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify .NET SDK
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore Blog.csproj

      - name: Build
        run: dotnet build Blog.csproj --configuration Release --no-restore

      - name: Publish to IIS
        run: dotnet publish Blog.csproj -c Release -o "C:\inetpub\wwwroot\Blog_pipeline"
